### ISSUE TITLE
Cropping function not working on iPhone 

### ISSUE THREAD

**Issue by tcmartinezmedia** [innostudio/fileuploader#16]
I seem to have found an issue pertaining to the cropping you can do with the fileuploader. When I tried to use my mobile device which is an iPhone 6, I hand an issue cropping the photo in my form. I wanted to double check to make sure it wasn't from my end and went to your site and tried to crop my photo and still the same thing. It looks like when it crops the picture in the thumbnail rotates and expands.

Update***

My developer took a look at it and found out that it is only doing this to vertical images because of the exif. The fileuploader doesn't recognize the orientation once uploaded so its registering it wrong once your crop and rotate the image. This is only occurring when you take a vertical image oppose to a horizontal one. So not sure if that helps but it at least narrows down the issue.

**Comment by nickdevigns** [comment]
I went on here to see if there was a solution to this as I bought this fileuploader plugin about a month ago to use for an app I'm developing and I can validate that I see the exact same issue you are experiencing when using both the XCode iOS simulator as well when using Safari on an iPhone to visit the site where I host the app and when performing the file upload and cropping the images down, it seems to crop from the top/left instead of the designated crop area drawn and also did not rotate the photo as originally set. There are no issues when performing the same functions with Safari or Chrome browsers, just on iOS itself via the Simulator or Safari web browser via iPhone. Let me know if you need any more information on this as I would like to be able to use this plugin to do the same as well

**Comment by nickdevigns** [comment]
Just took a look at your updated comments to see if this only happens with vertical images and I see that it doesn't crop properly with horizontal images as well on an iPhone device or the XCode simulator. I've attached a link to an app that currently under development that is using this plugin to show the various examples, with all the iOS examples giving bad cropping results, see attached screens and link (by checking search results page): http://creativearmada.com/production/petalert/
<img width="412" alt="screen shot 2017-11-28 at 9 55 06 pm" src="https://user-images.githubusercontent.com/8567417/33355806-0d6a43d2-d487-11e7-84c8-4cfb4642a686.png">
<img width="413" alt="screen shot 2017-11-28 at 9 55 31 pm" src="https://user-images.githubusercontent.com/8567417/33355807-0d73f2e2-d487-11e7-8ef8-799edebd8e31.png">

**Comment by innostudio** [comment]
@tcmartinezmedia and @nickdevigns we want to let you know that the issue should be solved in the last version. We are sorry that it took so long time to solve it.

**v2.2** - ([https://innostudio.de/fileuploader/documentation/#changelog](https://innostudio.de/fileuploader/documentation/#changelog))

Please update your Fileuploader.
